name: riverpod_infinity_scroll_list
description: Infinity scroll list implemetation with Riverpod

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  riverpod: ^2.2.0
  flutter_riverpod: ^2.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  riverpod_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true